import webpush from 'web-push';
export interface Env{DB:D1Database;DOCS:R2Bucket;APP_URL:string;TIMEZONE:string;ALERT_HOURS:string;DISCORD_CLIENT_ID:string;DISCORD_CLIENT_SECRET:string;DISCORD_REDIRECT_URI:string;DISCORD_WEBHOOK_URL:string;ADMIN_DISCORD_ID:string;SESSION_SECRET:string;VAPID_PUBLIC_KEY:string;VAPID_PRIVATE_KEY:string;VAPID_SUBJECT:string}
const security={'x-content-type-options':'nosniff','referrer-policy':'no-referrer','permissions-policy':'geolocation=(), camera=(), microphone=()','cache-control':'no-store'};
const json=(data:any,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8',...security,...headers}});
const cors=(env:Env)=>({'access-control-allow-origin':env.APP_URL,'access-control-allow-credentials':'true','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'});
const token=()=>crypto.randomUUID()+crypto.randomUUID();
async function me(req:Request,env:Env){const t=(req.headers.get('cookie')||'').match(/am_session=([^;]+)/)?.[1];if(!t)return null;return await env.DB.prepare("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>datetime('now')").bind(t).first<any>()}
async function body(req:Request){try{return await req.json<any>()}catch{return {}}}
async function audit(env:Env,u:any,action:string,type?:string,id?:any,payload?:any){await env.DB.prepare("INSERT INTO activity_log(user_id,action,entity_type,entity_id,payload) VALUES(?,?,?,?,?)").bind(u?.id||null,action,type||null,id?String(id):null,payload?JSON.stringify(payload):null).run()}
async function discordSend(env:Env,content:string){if(!env.DISCORD_WEBHOOK_URL)return null;const r=await fetch(env.DISCORD_WEBHOOK_URL+'?wait=true',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content,allowed_mentions:{parse:['roles']}})});if(!r.ok)throw new Error('Discord '+r.status);return await r.json<any>()}
async function discordDelete(env:Env,id?:string){if(!id||!env.DISCORD_WEBHOOK_URL)return;await fetch(env.DISCORD_WEBHOOK_URL+'/messages/'+id,{method:'DELETE'}).catch(()=>{})}
async function pushAll(env:Env,title:string,bodyText:string){if(!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_KEY)return;webpush.setVapidDetails(env.VAPID_SUBJECT,env.VAPID_PUBLIC_KEY,env.VAPID_PRIVATE_KEY);const {results}=await env.DB.prepare("SELECT * FROM push_subscriptions").all<any>();for(const s of results){try{await webpush.sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},JSON.stringify({title,body:bodyText,url:env.APP_URL}))}catch(e:any){if(e?.statusCode===404||e?.statusCode===410)await env.DB.prepare("DELETE FROM push_subscriptions WHERE id=?").bind(s.id).run()}}}
async function alerts(env:Env){const {results}=await env.DB.prepare("SELECT a.*,s.last_threshold,s.discord_message_id FROM assets a LEFT JOIN alert_state s ON s.asset_id=a.id WHERE a.active=1 AND a.deleted_at IS NULL AND datetime(a.expires_at)>datetime('now')").all<any>();const hs=env.ALERT_HOURS.split(',').map(Number).sort((a,b)=>b-a);for(const a of results){const left=(new Date(a.expires_at).getTime()-Date.now())/36e5;const th=[...hs].reverse().find(h=>left<=h);if(th==null||a.last_threshold===th)continue;await discordDelete(env,a.discord_message_id);const role=a.discord_role_id?'<@&'+a.discord_role_id+'> ':'';const text=role+'⏳ **'+a.name+'** wygasa za około **'+th+'h**.\nTermin: '+new Date(a.expires_at).toLocaleString('pl-PL',{timeZone:env.TIMEZONE});const msg=await discordSend(env,text);await env.DB.prepare("INSERT INTO alert_state(asset_id,last_threshold,discord_message_id,last_sent_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(asset_id) DO UPDATE SET last_threshold=excluded.last_threshold,discord_message_id=excluded.discord_message_id,last_sent_at=CURRENT_TIMESTAMP").bind(a.id,th,msg?.id||null).run();await env.DB.prepare("INSERT INTO notifications(title,body) VALUES(?,?)").bind(a.name,'Termin za około '+th+'h').run();await pushAll(env,a.name,'Termin wygasa za około '+th+'h')}}
async function api(req:Request,env:Env):Promise<Response>{const url=new URL(req.url),p=url.pathname;if(req.method==='OPTIONS')return new Response(null,{headers:{...security,...cors(env)}});const len=Number(req.headers.get('content-length')||0);if(len>8*1024*1024)return json({error:'Żądanie jest za duże'},413,cors(env));if(p.startsWith('/api/')&&!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.get('origin')!==env.APP_URL)return json({error:'Nieprawidłowe źródło żądania'},403,cors(env));
if(p==='/health')return json({ok:true,time:new Date().toISOString()});
if(p==='/auth/discord'){const state=token();const q=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:env.DISCORD_REDIRECT_URI,scope:'identify',state});return new Response(null,{status:302,headers:{location:'https://discord.com/oauth2/authorize?'+q,'set-cookie':'oauth_state='+state+'; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=600'}})}
if(p==='/auth/discord/callback'){const code=url.searchParams.get('code'),state=url.searchParams.get('state'),saved=(req.headers.get('cookie')||'').match(/oauth_state=([^;]+)/)?.[1];if(!code||!state||state!==saved)return json({error:'Nieprawidłowy OAuth state'},400);const form=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,client_secret:env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:env.DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});const td=await tr.json<any>();if(!td.access_token)return json({error:'OAuth failed'},401);const dr=await fetch('https://discord.com/api/users/@me',{headers:{authorization:'Bearer '+td.access_token}});const d=await dr.json<any>();const role=d.id===env.ADMIN_DISCORD_ID?'admin':'member',status='active';await env.DB.prepare("INSERT INTO users(discord_id,discord_name,avatar,role,status) VALUES(?,?,?,?,?) ON CONFLICT(discord_id) DO UPDATE SET discord_name=excluded.discord_name,avatar=excluded.avatar,role=excluded.role,status=excluded.status,updated_at=CURRENT_TIMESTAMP").bind(d.id,d.username,d.avatar,role,status).run();const u=await env.DB.prepare("SELECT * FROM users WHERE discord_id=?").bind(d.id).first<any>();const st=token(),exp=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)").bind(st,u.id,exp).run();return new Response(null,{status:302,headers:{location:env.APP_URL,'set-cookie':'am_session='+st+'; HttpOnly; Secure; SameSite=None; Path=/; Max-Age=2592000'}})}
const u=await me(req,env);if(!u)return json({error:'UNAUTHORIZED'},401,cors(env));if(u.status!=='active'&&p!=='/api/me')return json({error:'PENDING'},403,cors(env));
if(p==='/api/me')return json(u,200,cors(env));
if(p==='/api/characters/claim'&&req.method==='POST'){
 if(u.character_name)return json({error:'Postać jest już przypisana do tego konta'},409,cors(env));
 const b=await body(req),name=String(b.character_name||'').trim().replace(/\s+/g,' ');
 if(name.length<3||name.length>60||!/^[-A-Za-zÀ-ž' ]+$/.test(name)||name.split(' ').length<2)return json({error:'Wpisz imię i nazwisko postaci'},400,cors(env));
 try{await env.DB.prepare("UPDATE users SET character_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND character_name IS NULL").bind(name,u.id).run()}catch{return json({error:'Ta postać została już zajęta'},409,cors(env))}
 const fresh=await env.DB.prepare("SELECT character_name FROM users WHERE id=?").bind(u.id).first<any>();
 if(fresh?.character_name!==name)return json({error:'Nie udało się przypisać postaci'},409,cors(env));
 await env.DB.prepare("INSERT OR IGNORE INTO money_balances(owner,clean,dirty) VALUES(?,0,0)").bind(name).run();
 await audit(env,u,'claim_character','user',u.id,{character_name:name});
 return json({ok:true,character_name:name},200,cors(env))
}
if(p==='/api/bootstrap'&&req.method==='GET'){await env.DB.prepare("INSERT OR IGNORE INTO money_balances(owner,clean,dirty) SELECT character_name,0,0 FROM users WHERE character_name IS NOT NULL").run();const moneyQ=u.role==='admin'?env.DB.prepare("SELECT mb.* FROM money_balances mb WHERE mb.owner='Wspólne' OR EXISTS(SELECT 1 FROM users x WHERE x.character_name=mb.owner) ORDER BY CASE WHEN mb.owner='Wspólne' THEN 1 ELSE 0 END, mb.owner"):env.DB.prepare("SELECT * FROM money_balances WHERE owner=?").bind(u.character_name);const [assets,money,events,sales,notifications]=await Promise.all([env.DB.prepare("SELECT * FROM assets WHERE deleted_at IS NULL ORDER BY expires_at").all(),moneyQ.all(),env.DB.prepare("SELECT * FROM calendar_events WHERE deleted_at IS NULL ORDER BY starts_at").all(),env.DB.prepare("SELECT s.*,p.name buyer_name,p.cid FROM sales s JOIN players p ON p.id=s.player_id WHERE s.deleted_at IS NULL ORDER BY s.created_at DESC").all(),env.DB.prepare("SELECT * FROM notifications WHERE user_id IS NULL OR user_id=? ORDER BY created_at DESC LIMIT 50").bind(u.id).all()]);return json({user:u,assets:assets.results,money:money.results,events:events.results,sales:sales.results,notifications:notifications.results},200,cors(env))}
if(p==='/api/assets'&&req.method==='POST'){const b=await body(req);const allowed=['Pole','Zagroda','Lombard','LS Motors','Mechanik'];if(!b.name||String(b.name).length>80||!allowed.includes(b.category)||!b.expires_at||isNaN(Date.parse(b.expires_at)))return json({error:'Nieprawidłowe dane'},400,cors(env));const r=await env.DB.prepare("INSERT INTO assets(name,category,expires_at,discord_role_id,created_by) VALUES(?,?,?,?,?)").bind(b.name,b.category,b.expires_at,b.discord_role_id||null,u.id).run();await audit(env,u,'create','asset',r.meta.last_row_id,b);return json({ok:true,id:r.meta.last_row_id},201,cors(env))}
const am=p.match(/^\/api\/assets\/(\d+)\/renew$/);if(am&&req.method==='POST'){const id=+am[1],b=await body(req),a=await env.DB.prepare("SELECT * FROM assets WHERE id=?").bind(id).first<any>();if(!a)return json({error:'Nie znaleziono'},404,cors(env));await env.DB.batch([env.DB.prepare("INSERT INTO renewals(asset_id,old_expires_at,new_expires_at,cost,user_id) VALUES(?,?,?,?,?)").bind(id,a.expires_at,b.expires_at,Number(b.cost)||0,u.id),env.DB.prepare("UPDATE assets SET expires_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.expires_at,id)]);const st=await env.DB.prepare("SELECT discord_message_id FROM alert_state WHERE asset_id=?").bind(id).first<any>();await discordDelete(env,st?.discord_message_id);await env.DB.prepare("DELETE FROM alert_state WHERE asset_id=?").bind(id).run();await audit(env,u,'renew','asset',id,b);return json({ok:true},200,cors(env))}
if(p==='/api/money'&&req.method==='POST'){const b=await body(req),owner=String(b.owner||'');if(u.role!=='admin'&&owner!==u.character_name)return json({error:'Możesz edytować tylko własne pieniądze'},403,cors(env));const old=await env.DB.prepare("SELECT * FROM money_balances WHERE owner=?").bind(owner).first<any>();if(!old)return json({error:'Nieznany właściciel'},400,cors(env));await env.DB.batch([env.DB.prepare("INSERT INTO money_log(owner,old_clean,old_dirty,new_clean,new_dirty,user_id) VALUES(?,?,?,?,?,?)").bind(owner,old.clean,old.dirty,Number(b.clean)||0,Number(b.dirty)||0,u.id),env.DB.prepare("UPDATE money_balances SET clean=?,dirty=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE owner=?").bind(Number(b.clean)||0,Number(b.dirty)||0,u.id,owner)]);return json({ok:true},200,cors(env))}
if(p==='/api/money/undo'&&req.method==='POST'){const q=u.role==='admin'?env.DB.prepare("SELECT * FROM money_log WHERE undone=0 ORDER BY id DESC LIMIT 1"):env.DB.prepare("SELECT * FROM money_log WHERE undone=0 AND owner=? ORDER BY id DESC LIMIT 1").bind(u.character_name);const l=await q.first<any>();if(!l)return json({error:'Brak zmian'},404,cors(env));await env.DB.batch([env.DB.prepare("UPDATE money_balances SET clean=?,dirty=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE owner=?").bind(l.old_clean,l.old_dirty,u.id,l.owner),env.DB.prepare("UPDATE money_log SET undone=1 WHERE id=?").bind(l.id)]);return json({ok:true},200,cors(env))}
if(p==='/api/events'&&req.method==='POST'){const b=await body(req);const r=await env.DB.prepare("INSERT INTO calendar_events(title,starts_at,ends_at,created_by) VALUES(?,?,?,?)").bind(b.title,b.starts_at,b.ends_at||null,u.id).run();return json({ok:true,id:r.meta.last_row_id},201,cors(env))}
if(p==='/api/sales'&&req.method==='POST'){const fd=await req.formData(),cid=String(fd.get('cid')||''),name=String(fd.get('buyer_name')||'');if(!cid||!name)return json({error:'CID i kupujący są wymagani'},400,cors(env));await env.DB.prepare("INSERT INTO players(cid,name) VALUES(?,?) ON CONFLICT(cid) DO UPDATE SET name=excluded.name,updated_at=CURRENT_TIMESTAMP").bind(cid,name).run();const pl=await env.DB.prepare("SELECT id FROM players WHERE cid=?").bind(cid).first<any>();const count=await env.DB.prepare("SELECT COUNT(*) c FROM sales WHERE strftime('%Y',created_at)=strftime('%Y','now')").first<any>();const no='LSM/'+new Date().getFullYear()+'/'+String((count?.c||0)+1).padStart(4,'0');let key:string|null=null;const file=fd.get('document');if(file instanceof File&&file.size){if(file.size>7*1024*1024||!['application/pdf','image/jpeg','image/png'].includes(file.type))return json({error:'Dozwolone są PDF/JPG/PNG do 7 MB'},400,cors(env));key='contracts/'+no.replaceAll('/','-')+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');await env.DOCS.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}})}await env.DB.prepare("INSERT INTO sales(contract_no,player_id,vehicle_name,registration,purchase_date,price,payment_method,extra_terms,seller_user_id,document_key) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(no,pl.id,String(fd.get('vehicle_name')||''),String(fd.get('registration')||''),String(fd.get('purchase_date')||''),Number(fd.get('price'))||0,String(fd.get('payment_method')||'Gotówka'),String(fd.get('extra_terms')||''),u.id,key).run();return json({ok:true,contract_no:no},201,cors(env))}
const pm=p.match(/^\/api\/players\/([^/]+)$/);if(pm){const cid=decodeURIComponent(pm[1]);const player=await env.DB.prepare("SELECT * FROM players WHERE cid=?").bind(cid).first<any>();if(!player)return json({error:'Nie znaleziono'},404,cors(env));const sales=await env.DB.prepare("SELECT * FROM sales WHERE player_id=? AND deleted_at IS NULL ORDER BY purchase_date DESC").bind(player.id).all();return json({player,sales:sales.results},200,cors(env))}
const dm=p.match(/^\/api\/documents\/(\d+)$/);if(dm){const s=await env.DB.prepare("SELECT document_key FROM sales WHERE id=?").bind(+dm[1]).first<any>();if(!s?.document_key)return json({error:'Brak dokumentu'},404,cors(env));const o=await env.DOCS.get(s.document_key);if(!o)return json({error:'Brak pliku'},404,cors(env));return new Response(o.body,{headers:{...security,'content-type':o.httpMetadata?.contentType||'application/octet-stream','content-disposition':'inline','x-frame-options':'SAMEORIGIN'}})}
if(p==='/api/push/subscribe'&&req.method==='POST'){const b=await body(req);await env.DB.prepare("INSERT INTO push_subscriptions(user_id,endpoint,p256dh,auth) VALUES(?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth").bind(u.id,b.endpoint,b.keys?.p256dh,b.keys?.auth).run();return json({ok:true},200,cors(env))}
if(p==='/api/admin/test-discord'&&req.method==='POST'){if(u.role!=='admin')return json({error:'FORBIDDEN'},403,cors(env));if(!env.DISCORD_WEBHOOK_URL)return json({error:'Brak DISCORD_WEBHOOK_URL'},400,cors(env));try{await discordSend(env,'✅ **Holdings Panel** — test webhooka zakończony powodzeniem.');return json({ok:true},200,cors(env))}catch(e:any){return json({error:'Webhook Discord nie odpowiedział poprawnie'},502,cors(env))}
if(p==='/api/admin/users'&&u.role==='admin'){if(req.method==='GET'){const x=await env.DB.prepare("SELECT id,discord_id,discord_name,character_name,role,status FROM users ORDER BY created_at DESC").all();return json(x.results,200,cors(env))}if(req.method==='POST'){const b=await body(req);await env.DB.prepare("UPDATE users SET character_name=?,role=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.character_name,b.role||'member',b.status||'active',b.id).run();return json({ok:true},200,cors(env))}}
if(p==='/api/export'&&u.role==='admin'){const data:any={};for(const t of ['users','assets','renewals','money_balances','money_log','calendar_events','players','sales','activity_log'])data[t]=(await env.DB.prepare('SELECT * FROM '+t).all()).results;return json(data,200,{...cors(env),'content-disposition':'attachment; filename=holdings-panel-export.json'})}
return json({error:'NOT_FOUND'},404,cors(env))}
export default{fetch:api,async scheduled(_c:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(alerts(env))}};